### PR TITLE
Rfc7405

### PR DESCRIPTION
**Pull request by guenni68**
Using RFC7405 compliant notation for denoting case-sensitive string literals, ie: %s"aBc"

### CODE REVIEW

**Review by ralfhandl — CHANGES_REQUESTED** [review]
Hi @guenni68,

Thanks for providing this PR. I like the idea in principle, unfortunately merging this PR as is would break our ABNF test cases.

Reason: the underlying [ABNF Parser Generator](https://github.com/ldthomas/apg-java) uses single quotes to denote case-sensitive literal strings.

So until a newer version of `apg-java` accepting RFC7405 syntax is available, I'll have to keep this PR on hold.

Thanks!
Ralf

**Comment by greggirwin** [comment]
I sent an email to @ralfhandl and @mikepizzo a couple weeks ago, about generated syntax diagrams we did for the OData ABNF, but it may have been eaten by spam filters. We created a metagrammar for the format used currently. @guenni68 do you know if RFC7405 is used by anyone in the wild? If so, and there's interest, we can look at adding support for it in our tool.

**Comment by greggirwin** [comment]
We added RFC7405 support to our ABNF grammar, since it was easy.

**Comment by ralfhandl** [comment]
Added RFC7405 support to https://github.com/ralfhandl/apg-java, so I can merge this.

@guenni68 Thanks for providing this PR!

**Pull request merged**
